In [2]:
import numpy as np

1. Create a NumPy array arr of integers from 0 to 5 and print its data type

In [3]:
arr = np.array([0, 1, 2, 3, 4, 5])
print("Array:", arr)
print("Data type:", arr.dtype)

Array: [0 1 2 3 4 5]
Data type: int32


2. Given a NumPy array arr, check if its data type is float64.

In [4]:
if arr.dtype == np.float64:
    print("The array is of type float64.")
else:
    print("The array is not of type float64.")

The array is not of type float64.


3. Create a NumPy array arr with data type complex128 containing three complex numbers

In [5]:
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print("Array:", arr)
print("Data type:", arr.dtype)

Array: [1.+2.j 3.+4.j 5.+6.j]
Data type: complex128


4. Convert an existing NumPy array arr of integers to float32 data type.

In [6]:
arr = np.array([1, 2, 3, 4])  
converted = arr.astype(np.float32)
print("Converted array:", converted)
print("Data type:", converted.dtype)

Converted array: [1. 2. 3. 4.]
Data type: float32


5. Convert arr from float64 to float32 to reduce decimal precision.

In [7]:
arr = np.array([1.23456789, 2.3456789], dtype=np.float64)
converted = arr.astype(np.float32)
print("Original (float64):", arr)
print("Converted (float32):", converted)

Original (float64): [1.23456789 2.3456789 ]
Converted (float32): [1.2345679 2.3456788]


6. Function array_attributes returns shape, size, and data type.

In [8]:
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

a = np.array([[1, 2], [3, 4]])
print("Attributes:", array_attributes(a))

Attributes: ((2, 2), 4, dtype('int32'))


7. Function array_dimension returns the dimensionality

In [9]:
def array_dimension(arr):
    return arr.ndim

a = np.array([[1, 2], [3, 4]])
print("Dimension:", array_dimension(a))

Dimension: 2


8. Function item_size_info returns item size and total size in bytes.

In [10]:
def item_size_info(arr):
    return arr.itemsize, arr.nbytes

a = np.array([1, 2, 3], dtype=np.int32)
print("Item size and total size:", item_size_info(a))

Item size and total size: (4, 12)


9. Function array_strides returns the strides of the given array.

In [11]:
def array_strides(arr):
    return arr.strides

a = np.array([[1, 2], [3, 4]])
print("Strides:", array_strides(a))

Strides: (8, 4)


10. Function shape_stride_relationship returns shape and strides.

In [12]:
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

a = np.array([[1, 2], [3, 4]])
print("Shape and strides:", shape_stride_relationship(a))

Shape and strides: ((2, 2), (8, 4))


11. Function create_zeros_array(n) – Returns a NumPy array of zeros with n elements.

In [13]:
def create_zeros_array(n):
    return np.zeros(n)

print("Zeros array:", create_zeros_array(5))

Zeros array: [0. 0. 0. 0. 0.]


12. Function create_ones_matrix(rows, cols) – Returns a 2D array filled with ones.

In [14]:
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

print("Ones matrix:\n", create_ones_matrix(3, 4))

Ones matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


13. Function generate_range_array(start, stop, step) – Returns a ranged NumPy array.

In [15]:
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

print("Range array:", generate_range_array(1, 10, 2))

Range array: [1 3 5 7 9]


14. Function generate_linear_space(start, stop, num) – Generates num equally spaced values.

In [16]:
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

print("Linear spaced values:", generate_linear_space(0, 10, 5))

Linear spaced values: [ 0.   2.5  5.   7.5 10. ]


15. Function create_identity_matrix(n) – Creates an identity matrix using np.eye.

In [17]:
def create_identity_matrix(n):
    return np.eye(n)

print("Identity matrix:\n", create_identity_matrix(4))

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


16. Function to convert a Python list into a NumPy array.

In [18]:
def list_to_numpy_array(py_list):
    return np.array(py_list)

my_list = [1, 2, 3, 4, 5]
print("NumPy array:", list_to_numpy_array(my_list))

NumPy array: [1 2 3 4 5]


17. Create a NumPy array and use .view() to create a new view with the same data.

In [19]:
arr = np.array([10, 20, 30, 40])
arr_view = arr.view()

print("Original array:", arr)
print("View of the array:", arr_view)

Original array: [10 20 30 40]
View of the array: [10 20 30 40]


18. Function to concatenate two NumPy arrays along a specified axis.

In [20]:
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print("Concatenated along axis 0:\n", concatenate_arrays(a, b, axis=0))
print("Concatenated along axis 1:\n", concatenate_arrays(a, b, axis=1))

Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


19. Concatenate two arrays with different shapes horizontally using numpy.concatenate.

In [21]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

h_concat = np.concatenate((a, b), axis=1)
print("Horizontally concatenated arrays:\n", h_concat)

Horizontally concatenated arrays:
 [[1 4]
 [2 5]
 [3 6]]


20. Vertically stack multiple arrays from a list using numpy.vstack.

In [22]:
arrays = [np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])]
vstacked = np.vstack(arrays)
print("Vertically stacked arrays:\n", vstacked)

Vertically stacked arrays:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


21. Function to generate an array of integers within a specified range (inclusive) with a step.

In [23]:
def generate_integer_range(start, stop, step):
    return np.arange(start, stop + 1, step) 

print("Integer range:", generate_integer_range(1, 10, 2))

Integer range: [1 3 5 7 9]


22. Generate 10 equally spaced values between 0 and 1 using NumPy.

In [24]:
equally_spaced = np.linspace(0, 1, 10)
print("10 equally spaced values between 0 and 1:", equally_spaced)

10 equally spaced values between 0 and 1: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


23. Create 5 logarithmically spaced values between 1 and 1000.

In [25]:
log_spaced = np.logspace(0, 3, 5)
print("5 logarithmically spaced values between 1 and 1000:", log_spaced)

5 logarithmically spaced values between 1 and 1000: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [26]:
import numpy as np
import pandas as pd

24. Create a Pandas DataFrame from a NumPy array with 5 rows and 3 columns of random integers (1–100).

In [27]:
array = np.random.randint(1, 101, size=(5, 3))

df = pd.DataFrame(array, columns=['A', 'B', 'C'])

print("DataFrame with random integers:\n", df)

DataFrame with random integers:
     A   B   C
0  91  96  58
1  75  50  17
2  69  24  28
3  57  20  91
4  45  45  12


25. Function to replace all negative values in a specific column with zeros using NumPy.

In [28]:
def replace_negatives_with_zero(arr, column_index):
    arr_copy = arr.copy()
    arr_copy[arr_copy[:, column_index] < 0, column_index] = 0
    return arr_copy

sample_array = np.array([[1, -5, 3],
                         [-2, 6, -7],
                         [4, -1, 9]])

print("Original array:\n", sample_array)

updated_array = replace_negatives_with_zero(sample_array, 1)
print("Updated array (negatives in column 1 replaced with 0):\n", updated_array)

Original array:
 [[ 1 -5  3]
 [-2  6 -7]
 [ 4 -1  9]]
Updated array (negatives in column 1 replaced with 0):
 [[ 1  0  3]
 [-2  6 -7]
 [ 4  0  9]]


26. Access the 3rd element from a given NumPy array.

In [29]:
arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]  
print("3rd element:", third_element)

3rd element: 30


27. Retrieve the element at index (1, 2) from a 2D array.

In [30]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

element = arr_2d[1, 2]
print("Element at (1, 2):", element)

Element at (1, 2): 6


28. Extract elements greater than 5 using boolean indexing.

In [31]:
arr = np.array([2, 5, 7, 1, 9, 3])
greater_than_five = arr[arr > 5]
print("Elements > 5:", greater_than_five)

Elements > 5: [7 9]


29. Slice elements from index 2 to 5 (inclusive) from a NumPy array.

In [32]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
sliced = arr[2:6]  
print("Sliced elements (2 to 5):", sliced)

Sliced elements (2 to 5): [30 40 50 60]


30. Slice the sub-array [[2, 3], [5, 6]] from a 2D array.

In [33]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

sub_array = arr_2d[0:2, 1:3]
print("Sub-array:\n", sub_array)

Sub-array:
 [[2 3]
 [5 6]]


31. Extract elements based on indices from a 2D array.

In [34]:
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

indices = [0, 4, 8]  # These refer to flattened positions
extracted = arr_2d.flatten()[indices]
print("Extracted elements:", extracted)

Extracted elements: [10 50 90]


32. Filter elements greater than a threshold using boolean indexing.

In [35]:
arr = np.array([1, 5, 8, 3, 10, 6])
threshold = 5
filtered = arr[arr > threshold]
print("Elements greater than", threshold, ":", filtered)

Elements greater than 5 : [ 8 10  6]


33. Extract specific elements from a 3D array using separate index arrays.

In [36]:
arr_3d = np.arange(27).reshape((3, 3, 3))

i = np.array([0, 1, 2])
j = np.array([1, 0, 2])
k = np.array([2, 1, 0])

elements = arr_3d[i, j, k]
print("Extracted elements from 3D array:", elements)

Extracted elements from 3D array: [ 5 10 24]


34. Return elements satisfying two boolean conditions.

In [37]:
arr = np.array([1, 4, 7, 10, 13, 16])

result = arr[(arr > 5) & (arr < 15)]
print("Elements > 5 and < 15:", result)

Elements > 5 and < 15: [ 7 10 13]


35. Extract elements from a 2D array using separate row and column index arrays.

In [38]:
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

rows = np.array([0, 1, 2])
cols = np.array([2, 1, 0])

result = arr_2d[rows, cols]
print("Extracted elements using row and column indices:", result)

Extracted elements using row and column indices: [30 50 70]


36. Add scalar 5 to every element of an array using broadcasting.

In [39]:
arr = np.array([1, 2, 3, 4])
result = arr + 5
print("Array after adding 5:", result)

Array after adding 5: [6 7 8 9]


37. Multiply each row of a (3, 4) array by corresponding elements of a (1, 3) array.

In [40]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

row_factors = np.array([[2, 3, 4]])  
result = arr * row_factors.T        

print("Result of row-wise multiplication:\n", result)

Result of row-wise multiplication:
 [[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


38. Add a (1, 4) array to every row of a (4, 3) array using broadcasting.

In [41]:
base = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])  

adder = np.array([[100, 200, 300, 400]]) 

result = (base.T + adder).T
print("Result of broadcasting addition:\n", result)

Result of broadcasting addition:
 [[101 102 103]
 [204 205 206]
 [307 308 309]
 [410 411 412]]


39. Add two arrays of shapes (3, 1) and (1, 3) using broadcasting.

a = np.array([[1], [2], [3]])  # Shape (3,1)
b = np.array([[10, 20, 30]])   # Shape (1,3)

result = a + b  # Broadcasts to shape (3,3)
print("Broadcasted addition result:\n", result)

40. Handle shape incompatibility during multiplication between (2, 3) and (2, 2).

In [45]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])  

b = np.array([[10, 20],
              [30, 40]]) 

try:
    result = a * b  
except ValueError as e:
    print("Error:", e)
    print("To fix: reshape or align shapes using broadcasting rules.")

Error: operands could not be broadcast together with shapes (2,3) (2,2) 
To fix: reshape or align shapes using broadcasting rules.


41. Calculate column-wise mean of a 2D array

In [43]:
col_mean = np.mean(arr, axis=0)
print("Column-wise mean:", col_mean)

Column-wise mean: [5. 6. 7. 8.]


In [46]:
# 42. Find maximum value in each row
row_max = np.max(arr, axis=1)
print("Maximum value in each row:", row_max)

Maximum value in each row: [ 4  8 12]


In [47]:
# 43. Find indices of maximum values in each column
col_max_indices = np.argmax(arr, axis=0)
print("Indices of max values in each column:", col_max_indices)

Indices of max values in each column: [2 2 2 2]


In [48]:
# 44. Apply a custom function to compute moving sum along rows
def moving_sum(row, window=2):
    return np.convolve(row, np.ones(window, dtype=int), 'valid')

moving_sum_rows = np.apply_along_axis(moving_sum, axis=1, arr=arr)
print("Moving sum along rows:\n", moving_sum_rows)

Moving sum along rows:
 [[ 3  5  7]
 [11 13 15]
 [19 21 23]]


In [49]:
# 45. Check if all elements in each column are even
are_all_even_columns = np.all(arr % 2 == 0, axis=0)
print("All elements even in each column:", are_all_even_columns)

All elements even in each column: [False  True False  True]


In [50]:
# 46. Reshape a given array into dimensions m x n
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
reshaped = np.reshape(arr, (3, 2))  
print("Reshaped array:\n", reshaped)

Reshaped array:
 [[1 2]
 [3 4]
 [5 6]]


In [51]:
# 48. Concatenate two arrays along a specified axis
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
concat_axis0 = np.concatenate((arr1, arr2), axis=0)  # Vertically
concat_axis1 = np.concatenate((arr1, arr2), axis=1)  # Horizontally
print("Concatenated along axis 0:\n", concat_axis0)
print("Concatenated along axis 1:\n", concat_axis1)

Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [56]:
# 49. Split an array into sub-arrays along a specified axis
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80]])

split_cols = np.split(arr, 2, axis=1)
print("Split along columns:\n", split_cols)

split_rows = np.split(arr, 2, axis=0)
print("Split along rows:\n", split_rows)

unequal_split = np.array_split(arr, 3, axis=1)
print("Unequal split along columns:\n", unequal_split)

Split along columns:
 [array([[10, 20],
       [50, 60]]), array([[30, 40],
       [70, 80]])]
Split along rows:
 [array([[10, 20, 30, 40]]), array([[50, 60, 70, 80]])]
Unequal split along columns:
 [array([[10, 20],
       [50, 60]]), array([[30],
       [70]]), array([[40],
       [80]])]


In [55]:
# 50. Insert and delete elements at specified indices from an array
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr3 = np.array([10, 20, 30, 40, 50])
inserted = np.insert(arr3, 2, 99)
print("After insertion:", inserted)
deleted = np.delete(arr3, 3)
print("After deletion:", deleted)

After insertion: [10 20 99 30 40 50]
After deletion: [10 20 30 50]


In [57]:
# 51. Element-wise addition
arr1 = np.array([2, 4, 6, 8])
arr2 = np.array([1, 2, 3, 4])

addition = arr1 + arr2
print("Element-wise addition:", addition)

Element-wise addition: [ 3  6  9 12]


In [58]:
# 52. Element-wise subtraction (arr1 - arr2)
arr1 = np.array([2, 4, 6, 8])
arr2 = np.array([1, 2, 3, 4])

subtraction = arr1 - arr2
print("Element-wise subtraction:", subtraction)

Element-wise subtraction: [1 2 3 4]


In [59]:
# 53. Element-wise multiplication
arr1 = np.array([2, 4, 6, 8])
arr2 = np.array([1, 2, 3, 4])

division = arr1 / arr2
print("Element-wise division:", division)

Element-wise division: [2. 2. 2. 2.]


In [65]:
# 55. Element-wise exponentiation (arr1 ** arr2)
arr1 = np.array([2, 4, 6, 8])
arr2 = np.array([1, 2, 3, 4])

exponentiation = arr1 ** arr2
print("Element-wise exponentiation:",exponentiation)

Element-wise exponentiation: [   2   16  216 4096]


In [66]:
# 56. Count occurrences of a substring (e.g., "o") in each element
str_arr = np.array(['HelloWorld',  'NumPyIsFun', 'HELLO', 'world'])

count_o = np.char.count(str_arr, 'o')
print("Occurrences of 'o':", count_o)

Occurrences of 'o': [2 0 0 1]


In [63]:
# 57. Extract uppercase characters from each string
str_arr = np.array(['HelloWorld',  'NumPyIsFun', 'HELLO', 'world'])

uppercase_only = np.array([''.join([ch for ch in s if ch.isupper()]) for s in str_arr])
print("Uppercase characters:", uppercase_only)

Uppercase characters: ['HW' 'NPIF' 'HELLO' '']


In [64]:
# 58. Replace substring occurrences (e.g., "o" with "0")
str_arr = np.array(['HelloWorld',  'NumPyIsFun', 'HELLO', 'world'])

replaced = np.char.replace(str_arr, 'o', '0')
print("Replaced 'o' with '0':", replaced)

Replaced 'o' with '0': ['Hell0W0rld' 'NumPyIsFun' 'HELLO' 'w0rld']


In [69]:
# 59. Concatenate strings element-wise with another array
arr1 = np.array(['Data', 'Num', 'Py'])
arr2 = np.array(['Base', 'Py', 'thon'])

result = np.char.add(arr1, arr2)
print("Concatenated array:", result)

Concatenated array: ['DataBase' 'NumPy' 'Python']


In [68]:
# 60. Find the length of the longest string
str_arr = np.array(['HelloWorld',  'NumPyIsFun', 'HELLO', 'world'])

lengths = np.char.str_len(str_arr)
longest_length = np.max(lengths)
print("Length of the longest string:", longest_length)

Length of the longest string: 10


In [70]:
# 61. Generate 100 random integers (1–1000) and compute mean, median, variance, std deviation
data = np.random.randint(1, 1001, 100)

mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_dev = np.std(data)

print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

Mean: 475.36
Median: 410.5
Variance: 86239.51040000001
Standard Deviation: 293.66564388773844


In [71]:
# 62. Generate 50 random numbers (1–100) and compute the 25th and 75th percentiles
data = np.random.randint(1, 101, 50)

percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)

25th Percentile: 21.0
75th Percentile: 80.75


In [72]:
# 63. Compute correlation coefficient between two arrays using np.corrcoef
x = np.random.randint(10, 100, 20)
y = np.random.randint(10, 100, 20)

corr_matrix = np.corrcoef(x, y)
print("Correlation Coefficient Matrix:\n", corr_matrix)

Correlation Coefficient Matrix:
 [[ 1.        -0.1584177]
 [-0.1584177  1.       ]]


In [73]:
# 64. Perform matrix multiplication using np.dot
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

dot_product = np.dot(A, B)
print("Matrix Multiplication:\n", dot_product)

Matrix Multiplication:
 [[19 22]
 [43 50]]


In [74]:
# 65. Compute 10th, 50th, and 90th percentiles and quartiles for an array of 50 integers
data = np.random.randint(1, 100, 50)

p10 = np.percentile(data, 10)
p50 = np.percentile(data, 50)  # Also the median
p90 = np.percentile(data, 90)

q1 = np.percentile(data, 25)
q3 = np.percentile(data, 75)

print("10th Percentile:", p10)
print("50th Percentile (Median):", p50)
print("90th Percentile:", p90)
print("Q1 (25th):", q1)
print("Q3 (75th):", q3)

10th Percentile: 6.9
50th Percentile (Median): 60.5
90th Percentile: 80.30000000000001
Q1 (25th): 29.5
Q3 (75th): 74.5


In [75]:
# 66. Find index of a specific element in an array
arr = np.array([10, 20, 30, 40, 50])
index = np.where(arr == 30)[0] 
print("Index of 30:", index)

Index of 30: [2]


In [76]:
# 67. Sort a random array in ascending order

random_arr = np.random.randint(1, 100, 10)
sorted_arr = np.sort(random_arr)
print("Sorted array:", sorted_arr)

Sorted array: [ 6 17 41 43 54 56 57 58 78 93]


In [77]:
# 68. Filter elements greater than 20

arr = np.array([5, 12, 25, 30, 19, 50])
filtered = arr[arr > 20]
print("Elements > 20:", filtered)

Elements > 20: [25 30 50]


In [78]:
# 69. Filter elements divisible by 3

arr = np.array([3, 7, 9, 12, 14, 18, 21])
div_by_3 = arr[arr % 3 == 0]
print("Divisible by 3:", div_by_3)

Divisible by 3: [ 3  9 12 18 21]


In [79]:
# 70. Filter elements between 20 and 40 (inclusive)

arr = np.array([10, 22, 35, 41, 39, 50, 20])
filtered_range = arr[(arr >= 20) & (arr <= 40)]
print("Elements between 20 and 40:", filtered_range)


Elements between 20 and 40: [22 35 39 20]


In [81]:
# 71. Check byte order of a NumPy array using dtype.byteorder

arr = np.array([1, 2, 3], dtype=np.int16)

byte_order = arr.dtype.byteorder
print("Byte order:", byte_order)

Byte order: =


In [82]:
# 72. Perform in-place byte swapping using byteswap()

print("Original array:", arr)

arr.byteswap(inplace=True)
print("Byte-swapped array:", arr)

Original array: [1 2 3]
Byte-swapped array: [256 512 768]
